- name: Creating home directory
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - /opt/app1
    - /opt/app2

- name: Creating users
  user:
    name: "{{item}}"
    group: apps
    home: "/opt/{{item}}"
  with_items:
    - app1
    - app2
