- file:
    path: "{{item}}"
    state: directory
  with_items:
    - /opt/app1
    - /opt/app2
- user:
    name: "{{item.name}}"
    group: apps
    home: "{{item.home}}"
  with_items:
    - {name: 'app1', home: '/opt/app1'}
    - {name: 'app2', home: '/opt/app2'}
